service: hello-service # change to your service name

plugins:
  - serverless-pseudo-parameters # to work with pseudo parameters like #{AWS::Region}

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  region: eu-west-1 # change to your region
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: dist/index.hello
    events:
      - http:
          path: /hello
          method: GET
          cors: true
